import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

export type Language = 'km' | 'en';

export const translations = {
  en: {
    nav: {
      docs: 'Documentation',
      apis: 'APIs',
      demographics: 'Demographics',
      explorer: 'Explorer & Map',
      status: 'API Status',
      searchPlaceholder: 'Search 14,500+ locations...',
      openExplorer: 'Open Explorer',
      version: 'v1.0',
    },
    home: {
      badge: 'Free & Open Public REST APIs for Cambodia',
      heroTitle: 'Cambodian Administrative & Geographic Data API',
      heroSubtitle: 'Access 25 provinces, 210 districts, 1,661 communes, 14,528 villages, 5-digit postal codes, and official census demographics. Completely free without API keys.',
      exploreBtn: 'Interactive Explorer',
      docsBtn: 'View API Docs',
      statProvinces: 'Provinces & Capital',
      statDistricts: 'Districts (Khan/Srok)',
      statCommunes: 'Communes (Sangkat)',
      statVillages: 'Villages (Phum)',
      statPostal: 'Postal Codes',
      statPopulation: 'National Population',
      featuresTitle: 'Built for Modern Cambodian Developers',
      featuresSubtitle: 'High performance, sub-10ms response times, PostgreSQL relational accuracy, and official GIS boundaries.',
      feature1Title: 'Complete 4-Tier Hierarchy',
      feature1Desc: 'Provinces, districts, communes, and villages linked with ISO codes and native Khmer/English names.',
      feature2Title: '5-Digit Postal Codes',
      feature2Desc: 'Official Cambodia Post zip codes mapped to administrative zones for logistics, e-commerce, and courier delivery.',
      feature3Title: 'Standard GeoJSON Spatial Layers',
      feature3Desc: 'RFC 7946 GeoJSON boundary polygon and point layers ready to plug into Leaflet, Mapbox, or Google Maps.',
      feature4Title: 'Zero-Friction Free Access',
      feature4Desc: 'No registration, credit card, or API key needed. Public HTTPS endpoints with CORS enabled out of the box.',
      feature5Title: 'Bilingual Full-Text Search',
      feature5Desc: 'Instant trigram search across Khmer script, romanized names, postal codes, and administrative slugs.',
      feature6Title: 'Census & Demographics',
      feature6Desc: 'Historical population datasets from 1962 to 2024 and 25-province distribution estimates from NIS Ministry of Planning.',
      quickstartTitle: 'Quick API Start',
      quickstartDesc: 'Make your first request in seconds using your preferred language or cURL:',
    },
    apis: {
      title: 'API Catalog & Endpoints',
      subtitle: 'Browse all available public REST API endpoints with request parameters, schemas, and live testing.',
      filterAll: 'All Endpoints',
      filterAdmin: 'Administrative',
      filterPostal: 'Postal Codes',
      filterDemographics: 'Demographics',
      filterSpatial: 'GeoJSON Spatial',
      filterSearch: 'Search & Services',
      searchPlaceholder: 'Search endpoints by name, path, or keyword...',
      endpointCount: 'endpoints available',
      liveTestBtn: 'Send Request',
      viewInDocs: 'View in Docs',
    },
    demographics: {
      badge: 'Demographics API & Historical Dataset',
      title: 'Cambodia Population & Demographics',
      subtitle: 'Official population statistics of the Kingdom of Cambodia from 1962 to 2024 according to the General Population Census and surveys by the National Institute of Statistics (NIS), Ministry of Planning.',
      numeralEnglish: 'English Format (17.3M)',
      numeralKhmer: 'Khmer Format (១៧.៣ លាននាក់)',
      currentPop: 'Current Population (2024)',
      currentPopSub: '17,300,000 Total citizens',
      overallGrowth: 'Overall Growth (1962–2024)',
      overallGrowthSub: '3.03x increase from 5.7M base',
      annualRate: 'Annual Growth Rate',
      annualRateSub: 'Based on 2019-2024 census interval',
      censusCount: 'Census Milestones',
      censusCountSub: 'From 1962 to 2024',
      timelineTitle: 'Historical Population Timeline (1962 - 2024)',
      timelineDesc: 'Click on any year to inspect survey provenance and growth calculation',
      populationMil: 'Population (Millions)',
      provinceTableTitle: 'Population Distribution by Province (2024 Estimates)',
      provinceTableDesc: '25 Capital & Provinces breakdown based on NIS Cambodia',
      searchProvince: 'Search province...',
      colCode: 'Code',
      colProvinceEn: 'Province (English)',
      colProvinceKm: 'Province (Khmer)',
      colPopulation: 'Population',
      colShare: '% Share',
      apiTitle: 'Demographics REST API',
      apiDesc: 'Fetch demographic and population statistics formatted as JSON for your application or website.',
      testLiveBtn: 'Test Live API',
      fetching: 'Fetching from API...',
      jsonResponse: 'JSON Response',
      clientIntegration: 'Client Integration',
    },
    explorer: {
      title: 'Interactive API & Map Explorer',
      subtitle: 'Drill down through Cambodia 4-tier administrative hierarchy, inspect postal codes, and explore GIS GeoJSON boundary layers.',
      step1: '1. Province (ខេត្ត)',
      step2: '2. District (ស្រុក)',
      step3: '3. Commune (ឃុំ)',
      step4: '4. Village (ភូមិ)',
      selectProvince: 'Select a Province...',
      selectDistrict: 'Select a District...',
      selectCommune: 'Select a Commune...',
      selectVillage: 'Select a Village...',
      noDistricts: 'No districts found',
      noCommunes: 'No communes found',
      noVillages: 'No villages found',
      mapLayers: 'Map GeoJSON Layers',
      layerProvinces: 'Provinces Boundary',
      layerDistricts: 'Districts Boundary',
      layerCommunes: 'Communes Boundary',
      layerVillages: 'Villages Points',
      layerLakes: 'Lakes & Tonle Sap',
      layerParks: 'National Parks',
      entityDetails: 'Selected Region Details',
      postalCodes: 'Postal Codes',
      coordinates: 'Coordinates',
      directApiEndpoint: 'Direct API Endpoint',
      copyJson: 'Copy JSON Payload',
      resetSelection: 'Reset Filter',
    },
    docs: {
      title: 'KhmerAPI Documentation',
      subtitle: 'Comprehensive developer documentation with request parameters, schemas, multi-language code snippets, and in-place live testing.',
      baseUrlTitle: 'Base API URL',
      baseUrlDesc: 'All public endpoints are versioned under the /v1 prefix:',
      httpsRequired: 'HTTPS & CORS Enabled',
      zeroAuthTitle: 'Public & Free Access',
      zeroAuthDesc: 'No API keys or registration are required to consume any of the endpoints. You can immediately call the API from any frontend client, mobile app, or backend service.',
      responseFormatTitle: 'Standardized JSON Format',
      responseFormatDesc: 'Every endpoint returns an RFC 7807 compliant JSON payload containing success, data, and meta fields.',
      rateLimitsTitle: 'Rate Limits & Headers',
      rateLimitsDesc: 'Fair usage rate limits are tracked in real time using automated sliding-window counters.',
      parameters: 'Request Parameters',
      clientImplementation: 'Client Implementation',
      payloadPreview: 'Payload Preview',
      sendRequest: 'Send Request',
      testing: 'Testing API...',
      onThisPage: 'On this page',
      developerResources: 'Developer Resources',
      backToTop: 'Back to top',
      filterEndpoints: 'Filter endpoints...',
    },
    status: {
      title: 'System State & Live Latency',
      subtitle: 'Real-time telemetry, database health, system memory allocation, and automated endpoint responsiveness monitors.',
      allOperational: 'All Systems Operational',
      postgresDb: 'PostgreSQL Database',
      edgeGateway: 'Edge & Network Gateway',
      systemUptime: 'System Uptime',
      gatewayVersion: 'Gateway Version',
      activeEntities: 'Database Stored Entities',
      livePingsTitle: 'Live API Latency Monitor',
      livePingsDesc: 'Sub-millisecond endpoint pings measured live directly from your browser to the backend gateway.',
      recheckAll: 'Recheck Latency',
      checking: 'Pinging...',
      endpoint: 'Endpoint',
      method: 'Method',
      cached: 'Cache State',
      latency: 'Round-Trip Latency',
      status: 'Status',
    },
    footer: {
      tagline: 'Free & Open Public APIs for Cambodian Developers, Businesses, and Researchers.',
      navigation: 'Platform Navigation',
      resources: 'Developer Resources',
      legal: 'MIT License • Data sourced from official public records of the Kingdom of Cambodia.',
      allRights: 'KhmerAPI Platform. Built with pride for Cambodian developers',
    },
    common: {
      copy: 'Copy',
      copied: 'Copied',
      live: 'Live',
      free: 'Free',
      public: 'Public',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      open: 'Open',
      close: 'Close',
    },
  },
  km: {
    nav: {
      docs: 'ឯកសារ',
      apis: 'APIs',
      demographics: 'ប្រជាសាស្ត្រ',
      explorer: 'រុករក & ផែនទី',
      status: 'ស្ថានភាព API',
      searchPlaceholder: 'ស្វែងរកជាង ១៤,៥០០+ ទីតាំង...',
      openExplorer: 'បើកផ្ទាំងរុករក',
      version: 'ជំនាន់ ១.០',
    },
    home: {
      badge: 'API ឥតគិតថ្លៃ និងបើកចំហសម្រាប់អ្នកអភិវឌ្ឍន៍ខ្មែរ',
      heroTitle: 'ប្រព័ន្ធ REST API ទិន្នន័យរដ្ឋបាល និងភូមិសាស្ត្រកម្ពុជា',
      heroSubtitle: 'ផ្តល់ជូនទិន្នន័យពេញលេញ ២៥ រាជធានី-ខេត្ត, ២១០ ក្រុង-ស្រុក-ខណ្ឌ, ១,៦៦១ ឃុំ-សង្កាត់, ១៤,៥២៨ ភូមិ, លេខកូដប្រៃសណីយ៍ ៥ ខ្ទង់ និងស្ថិតិប្រជាសាស្ត្រជំរឿនផ្លូវការ។ ប្រើប្រាស់ដោយសេរី មិនបាច់ចុះឈ្មោះ មិនបាច់ប្រើ API Key។',
      exploreBtn: 'សាកល្បងរុករកទិន្នន័យ',
      docsBtn: 'មើលឯកសារបច្ចេកទេស',
      statProvinces: 'រាជធានី-ខេត្ត',
      statDistricts: 'ក្រុង-ស្រុក-ខណ្ឌ',
      statCommunes: 'ឃុំ-សង្កាត់',
      statVillages: 'ភូមិសរុប',
      statPostal: 'លេខកូដប្រៃសណីយ៍',
      statPopulation: 'ប្រជាជនសរុប',
      featuresTitle: 'រចនាឡើងយ៉ាងផ្ចិតផ្ចង់សម្រាប់ Developer កម្ពុជា',
      featuresSubtitle: 'ល្បឿនលឿនខ្ពស់ (Latency < 10ms) ជាមួយស្ថាបត្យកម្មទំនើប, ទិន្នន័យត្រឹមត្រូវតាមប្រព័ន្ធ PostgreSQL និងមានព្រំប្រទល់ GIS GeoJSON ពេញលេញ។',
      feature1Title: 'ឋានានុក្រមរដ្ឋបាល ៤ ថ្នាក់',
      feature1Desc: 'រាជធានី-ខេត្ត, ក្រុង-ស្រុក-ខណ្ឌ, ឃុំ-សង្កាត់ និងភូមិ តភ្ជាប់គ្នាជាមួយលេខកូដស្តង់ដារ ISO និងឈ្មោះពីរភាសា (ខ្មែរ-អង់គ្លេស)។',
      feature2Title: 'លេខកូដប្រៃសណីយ៍ ៥ ខ្ទង់',
      feature2Desc: 'លេខកូដប្រៃសណីយ៍ផ្លូវការរបស់ប្រៃសណីយ៍កម្ពុជា សម្រាប់វិស័យដឹកជញ្ជូន សេវាបញ្ញើ និង E-commerce។',
      feature3Title: 'ផែនទីទិន្នន័យ GeoJSON ស្តង់ដារ',
      feature3Desc: 'ស្រទាប់ព្រំប្រទល់ Polygon និងចំណុចកូអរដោនេ GeoJSON (RFC 7946) ងាយស្រួលដាក់លើ Leaflet, Mapbox ឬ Google Maps។',
      feature4Title: 'ប្រើប្រាស់ដោយឥតគិតថ្លៃ ១០០%',
      feature4Desc: 'មិនទាមទារការចុះឈ្មោះ មិនចាំបាច់មានកាតធនាគារ ឬ API Key។ អាចហៅប្រើភ្លាមៗតាមរយៈ HTTPS និងបើក CORS រួចជាស្រេច។',
      feature5Title: 'ស្វែងរកល្បឿនលឿនពីរភាសា',
      feature5Desc: 'ស្វែងរកបានទាំងអក្សរខ្មែរ អក្សរឡាតាំង លេខកូដរដ្ឋបាល និងលេខប្រៃសណីយ៍ ដោយប្រើ Trigram Fuzzy Search។',
      feature6Title: 'ស្ថិតិជំរឿន និងប្រជាសាស្ត្រ',
      feature6Desc: 'ទិន្នន័យប្រជាជនជាប្រវត្តិសាស្ត្រពីឆ្នាំ១៩៦២ ដល់ ២០២៤ និងការបែងចែកតាមខេត្តពីវិទ្យាស្ថានជាតិស្ថិតិ ក្រសួងផែនការ។',
      quickstartTitle: 'ចាប់ផ្តើមប្រើប្រាស់រហ័ស',
      quickstartDesc: 'ធ្វើការហៅសាកល្បង API ដំបូងរបស់អ្នកជាមួយភាសាកម្មវិធីដែលអ្នកពេញចិត្ត ឬ cURL៖',
    },
    apis: {
      title: 'កាតាឡុក APIs & Endpoints ទាំងអស់',
      subtitle: 'ស្វែងរក និងសាកល្បង API endpoints ទាំងអស់ជាមួយប៉ារ៉ាម៉ែត្រ ទម្រង់ JSON និងការតេស្តផ្ទាល់។',
      filterAll: 'Endpoints ទាំងអស់',
      filterAdmin: 'ទិន្នន័យរដ្ឋបាល',
      filterPostal: 'លេខកូដប្រៃសណីយ៍',
      filterDemographics: 'ស្ថិតិប្រជាសាស្ត្រ',
      filterSpatial: 'ផែនទី GeoJSON',
      filterSearch: 'សេវាស្វែងរក & ស្ថិតិ',
      searchPlaceholder: 'ស្វែងរក Endpoint តាមឈ្មោះ ផ្លូវ ឬពាក្យគន្លឹះ...',
      endpointCount: 'Endpoints ដែលមាន',
      liveTestBtn: 'ផ្ញើសំណើ (Test)',
      viewInDocs: 'មើលក្នុង Docs',
    },
    demographics: {
      badge: 'ស្ថិតិប្រជាសាស្ត្រ & ទិន្នន័យប្រវត្តិសាស្ត្រ',
      title: 'ទិន្នន័យប្រជាសាស្ត្រ និងស្ថិតិប្រជាជនកម្ពុជា',
      subtitle: 'ទិន្នន័យស្ថិតិប្រជាជនផ្លូវការរបស់ព្រះរាជាណាចក្រកម្ពុជា ចាប់ពីឆ្នាំ១៩៦២ រហូតដល់បច្ចុប្បន្នឆ្នាំ២០២៤ យោងតាមជំរឿនទូទៅប្រជាជន និងរបាយការណ៍អង្កេតរបស់វិទ្យាស្ថានជាតិស្ថិតិ (NIS) នៃក្រសួងផែនការ។',
      numeralEnglish: 'ទម្រង់អង់គ្លេស (17.3M)',
      numeralKhmer: 'ទម្រង់លេខខ្មែរ (១៧.៣ លាននាក់)',
      currentPop: 'ប្រជាជនបច្ចុប្បន្ន (២០២៤)',
      currentPopSub: 'ស្មើនឹង ១៧,៣០០,០០០ នាក់សរុប',
      overallGrowth: 'កំណើនសរុប (១៩៦២-២០២៤)',
      overallGrowthSub: 'កើនឡើង ៣.០៣ ដងធៀបនឹងឆ្នាំ១៩៦២',
      annualRate: 'អត្រាកំណើនប្រចាំឆ្នាំ',
      annualRateSub: 'ផ្អែកលើចន្លោះជំរឿន ២០១៩-២០២៤',
      censusCount: 'ចំនួនលើកជំរឿនផ្លូវការ',
      censusCountSub: 'ពីឆ្នាំ១៩៦២ ដល់ ២០២៤',
      timelineTitle: 'តារាងប្រៀបធៀបការវិវត្តន៍ចំនួនប្រជាជន (១៩៦២ - ២០២៤)',
      timelineDesc: 'ចុចលើឆ្នាំនីមួយៗដើម្បីមើលព័ត៌មានលម្អិតនៃជំរឿន និងការគណនាកំណើន',
      populationMil: 'ចំនួនប្រជាជន (គិតជាលាននាក់)',
      provinceTableTitle: 'ការបែងចែកប្រជាជនតាមរាជធានី-ខេត្ត (២០២៤)',
      provinceTableDesc: 'ទិន្នន័យប្រមាណចំនួនប្រជាជនទាំង ២៥ រាជធានី-ខេត្ត ដោយវិទ្យាស្ថានជាតិស្ថិតិ',
      searchProvince: 'ស្វែងរកខេត្ត...',
      colCode: 'កូដ',
      colProvinceEn: 'រាជធានី-ខេត្ត (អង់គ្លេស)',
      colProvinceKm: 'រាជធានី-ខេត្ត (ខ្មែរ)',
      colPopulation: 'ចំនួនប្រជាជន',
      colShare: 'ភាគរយ (%)',
      apiTitle: 'Demographics REST API',
      apiDesc: 'ទាញយកទិន្នន័យប្រជាសាស្ត្រ និងស្ថិតិប្រជាជនជាទម្រង់ JSON សម្រាប់យកទៅប្រើប្រាស់ក្នុង App ឬ Website របស់អ្នក។',
      testLiveBtn: 'តេស្ត API ផ្ទាល់',
      fetching: 'កំពុងទាញទិន្នន័យពី API...',
      jsonResponse: 'លទ្ធផល JSON Response',
      clientIntegration: 'កូដគំរូសម្រាប់ Developer',
    },
    explorer: {
      title: 'ផ្ទាំងរុករកទិន្នន័យ & ផែនទីកម្ពុជា',
      subtitle: 'រុករកតាមឋានានុក្រម ៤ ថ្នាក់នៃកម្ពុជា ស្វែងរកលេខកូដប្រៃសណីយ៍ និងមើលស្រទាប់ព្រំប្រទល់ GeoJSON លើផែនទីអន្តរកម្ម។',
      step1: '១. ជ្រើសរើសរាជធានី-ខេត្ត',
      step2: '២. ជ្រើសរើសក្រុង-ស្រុក-ខណ្ឌ',
      step3: '៣. ជ្រើសរើសឃុំ-សង្កាត់',
      step4: '៤. ជ្រើសរើសភូមិ',
      selectProvince: 'ជ្រើសរើសរាជធានី-ខេត្ត...',
      selectDistrict: 'ជ្រើសរើសក្រុង-ស្រុក-ខណ្ឌ...',
      selectCommune: 'ជ្រើសរើសឃុំ-សង្កាត់...',
      selectVillage: 'ជ្រើសរើសភូមិ...',
      noDistricts: 'មិនមានស្រុក/ខណ្ឌទេ',
      noCommunes: 'មិនមានឃុំ/សង្កាត់ទេ',
      noVillages: 'មិនមានភូមិទេ',
      mapLayers: 'ស្រទាប់ផែនទី GeoJSON',
      layerProvinces: 'ព្រំប្រទល់ខេត្ត',
      layerDistricts: 'ព្រំប្រទល់ស្រុក/ខណ្ឌ',
      layerCommunes: 'ព្រំប្រទល់ឃុំ/សង្កាត់',
      layerVillages: 'ទីតាំងភូមិ',
      layerLakes: 'បឹង & បឹងទន្លេសាប',
      layerParks: 'ឧទ្យានជាតិ & ដែនជម្រក',
      entityDetails: 'ព័ត៌មានលម្អិតនៃតំបន់ដែលបានជ្រើសរើស',
      postalCodes: 'លេខកូដប្រៃសណីយ៍',
      coordinates: 'កូអរដោនេភូមិសាស្ត្រ',
      directApiEndpoint: 'Endpoint API ផ្ទាល់',
      copyJson: 'ចម្លងទិន្នន័យ JSON',
      resetSelection: 'កំណត់ឡើងវិញ',
    },
    docs: {
      title: 'ឯកសារបច្ចេកទេស KhmerAPI',
      subtitle: 'ការណែនាំលម្អិតសម្រាប់ Developer ជាមួយប៉ារ៉ាម៉ែត្រ ទម្រង់ JSON កូដគំរូគ្រប់ភាសា និងប្រព័ន្ធតេស្ត API ផ្ទាល់។',
      baseUrlTitle: 'Base API URL',
      baseUrlDesc: 'រាល់ Public Endpoints ទាំងអស់ស្ថិតនៅក្រោម path prefix /v1 ៖',
      httpsRequired: 'គាំទ្រ HTTPS & CORS រួចជាស្រេច',
      zeroAuthTitle: 'ប្រើប្រាស់ដោយឥតគិតថ្លៃ និងសេរី',
      zeroAuthDesc: 'មិនចាំបាច់មាន API Key ឬចុះឈ្មោះគណនីឡើយ។ អ្នកអាចហៅប្រើប្រាស់ភ្លាមៗពី Frontend, Mobile App ឬ Backend របស់អ្នក។',
      responseFormatTitle: 'ទម្រង់ស្តង់ដារ JSON Response',
      responseFormatDesc: 'រាល់ការឆ្លើយតបទាំងអស់មានទម្រង់ស្តង់ដារ RFC 7807 ដែលមាន success, data និង meta។',
      rateLimitsTitle: 'កម្រិតសំណើ (Rate Limits) & Headers',
      rateLimitsDesc: 'តាមដានកម្រិតសំណើដោយស្វ័យប្រវត្តិតាមរយៈ Sliding-Window Counter។',
      parameters: 'ប៉ារ៉ាម៉ែត្រសំណើ (Parameters)',
      clientImplementation: 'កូដគំរូហៅប្រើ (Client Code)',
      payloadPreview: 'ទម្រង់ទិន្នន័យ JSON Preview',
      sendRequest: 'ផ្ញើសំណើតេស្ត',
      testing: 'កំពុងតេស្ត API...',
      onThisPage: 'មាតិកាលើទំព័រនេះ',
      developerResources: 'ធនធានសម្រាប់ Developer',
      backToTop: 'ត្រឡប់ទៅលើវិញ',
      filterEndpoints: 'ស្វែងរក endpoints...',
    },
    status: {
      title: 'ស្ថានភាពប្រព័ន្ធ & ល្បឿនឆ្លើយតប (Latency)',
      subtitle: 'តាមដានសុខភាពម៉ាស៊ីនមេ មូលដ្ឋានទិន្នន័យ PostgreSQL និងល្បឿន Latency នៃគ្រប់ Endpoint ផ្ទាល់។',
      allOperational: 'ប្រព័ន្ធដំណើរការប្រក្រតី ១០០%',
      postgresDb: 'មូលដ្ឋានទិន្នន័យ PostgreSQL',
      edgeGateway: 'ច្រកទ្វារបណ្តាញ Edge & Gateway',
      systemUptime: 'ថិរវេលាដំណើរការ (Uptime)',
      gatewayVersion: 'ជំនាន់ Gateway',
      activeEntities: 'ចំនួនទិន្នន័យក្នុងប្រព័ន្ធ',
      livePingsTitle: 'តារាងវាស់ស្ទង់ល្បឿន Latency ផ្ទាល់',
      livePingsDesc: 'វាស់ស្ទង់ល្បឿន Round-Trip ពី Browser របស់អ្នកទៅកាន់ Server Backend ដោយផ្ទាល់។',
      recheckAll: 'ពិនិត្យល្បឿនឡើងវិញ',
      checking: 'កំពុងវាស់ស្ទង់...',
      endpoint: 'Endpoint',
      method: 'Method',
      cached: 'ស្ថានភាព Cache',
      latency: 'ល្បឿនឆ្លើយតប (Latency)',
      status: 'ស្ថានភាព',
    },
    footer: {
      tagline: 'ប្រព័ន្ធ API សាធារណៈឥតគិតថ្លៃសម្រាប់ Developer ក្រុមហ៊ុន និងអ្នកស្រាវជ្រាវកម្ពុជា។',
      navigation: 'ការរុករកទំព័រ',
      resources: 'ធនធានបច្ចេកវិទ្យា',
      legal: 'អាជ្ញាបណ្ណ MIT • ទិន្នន័យប្រភពផ្លូវការនៃព្រះរាជាណាចក្រកម្ពុជា។',
      allRights: 'KhmerAPI Platform. បង្កើតឡើងដោយមោទនភាពសម្រាប់សហគមន៍បច្ចេកវិទ្យាកម្ពុជា',
    },
    common: {
      copy: 'ចម្លង',
      copied: 'បានចម្លង',
      live: 'ផ្ទាល់',
      free: 'ឥតគិតថ្លៃ',
      public: 'សាធារណៈ',
      loading: 'កំពុងដំណើរការ...',
      error: 'មានបញ្ហា',
      success: 'ជោគជ័យ',
      open: 'បើក',
      close: 'បិទ',
    },
  },
};

export const useLangStore = defineStore('lang', () => {
  const storedLang = typeof window !== 'undefined' ? (localStorage.getItem('khmerapi_lang') as Language) : null;
  const currentLang = ref<Language>(storedLang || 'km');

  // Apply font family and HTML lang attribute to document
  function applyLanguageAttributes(lang: Language) {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = lang;
      if (lang === 'km') {
        document.body.classList.add('font-battambang');
      } else {
        document.body.classList.remove('font-battambang');
      }
    }
  }

  function setLang(lang: Language) {
    currentLang.value = lang;
    if (typeof window !== 'undefined') {
      localStorage.setItem('khmerapi_lang', lang);
    }
    applyLanguageAttributes(lang);
  }

  function toggleLang() {
    const next = currentLang.value === 'km' ? 'en' : 'km';
    setLang(next);
  }

  // Reactive translation dictionary
  const t = computed(() => {
    return translations[currentLang.value] || translations.en;
  });

  // Initialize on load
  if (typeof window !== 'undefined') {
    applyLanguageAttributes(currentLang.value);
  }

  return {
    currentLang,
    setLang,
    toggleLang,
    t,
  };
});
